"""add payment_method column

Revision ID: 0974acb119bd
Revises: 
Create Date: 2025-06-05 08:47:17.552848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0974acb119bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cashflow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('account_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cashflow', schema=None) as batch_op:
        batch_op.drop_column('account_name')
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
